### ISSUE TITLE
Listing recordings always show a single result

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/node#22]
I assume that `replay-recordings ls` should list all existing (or at least like X last) recordings. At the moment it only shows one.

I've recorded a replay and got such a result after running `replay-recordings ls`:
```json
[
  {
    "id": 1337562688,
    "createTime": "Mon Sep 20 2021 17:08:55 GMT+0200 (Central European Summer Time)",
    "runtime": "node",
    "metadata": {
      "argv": [
        "./node_modules/.bin/tsc",
        "--noEmit"
      ]
    },
    "status": "startedUpload",
    "path": "/Users/mateuszburzynski/.replay/recording-1337562688.dat",
    "server": "wss://dispatch.replay.io",
    "recordingId": "e47e0791-68a5-4bf9-bcaf-fb06e49c3a1d"
  }
]
```
then I've made a second recording (using the same script and all) and got this back:
```json
[
  {
    "id": 1337562688,
    "createTime": "Mon Sep 20 2021 17:08:55 GMT+0200 (Central European Summer Time)",
    "runtime": "node",
    "metadata": {
      "argv": [
        "./node_modules/.bin/tsc",
        "--noEmit"
      ]
    },
    "status": "startedUpload",
    "path": "/Users/mateuszburzynski/.replay/recording-1337562688.dat",
    "server": "wss://dispatch.replay.io",
    "recordingId": "2ca00a03-1a0e-496c-bbc0-3c08f0763007"
  }
]
```

Notice that `recordingId` is different (and IIRC it uploads as a new recording) but the rest is the same. `createTime` looks like the `createTime` of my very first node recording from yesterday.

I've actually made some small changes to the script I'm trying to debug since yesterday in the meantime. After uploading a new recording and going through the debugger I've noticed that I don't debug what I've expected to debug - I've realized that I'm debugging the old content of the script. That's what prompted this bug report.

**Comment by ryanjduffy** [comment]
@Andarist - Got to the bottom of this. The replay driver and the CLI were both appending to the recording log in a way that could corrupt part of the file resulting in recordings appearing to have been lost. In reality, all the recordings are still there but the log was confused.

Should have a fix rolled out soon and I'll note here when it is.

**Comment by Andarist** [comment]
@ryanjduffy thanks for the prompt reply! ye, I've seen all the recordings when I've located the directory containing them - I think the bug has caused an issue with which recording has been actually uploaded since I've uploaded "outdated" replay several times. After debugging for a while I've realized that I was debugging a wrong recording 😅

**Comment by ryanjduffy** [comment]
This should be fixed with version 0.4.1. I think should also fix re-uploading the same recording since the recording state should be parsed correctly now. Let me know if you're still running into issues!

https://www.npmjs.com/package/@recordreplay/recordings-cli/v/0.4.1

**Comment by Andarist** [comment]
A sideways note - it seems like the primary, documented, way to use this is the `@recordreplay/replay-node-cli`. It's a little bit not obvious that it contains those other ones, or rather that it fetches them and that probably its update command can be used to update the installed `@recordreplay/recordings-cli`

**Comment by ryanjduffy** [comment]
I'm not sure I follow. You're right that `@recordreplay/recordings-cli` is required to upload recordings created by `@recordreplay/replay-node-cli`. It's also used for recordings created by our playwright and puppeteer forks. It doesn't contain any of those runtimes though. They are managed separately by other packages.

Hope that helps but please let me know if I've misunderstood your note.

**Comment by Andarist** [comment]
Sorry for the reply. I was wrong - I totally forgot that I've actually installed `@recordreplay/recordings-cli` explicitly, I have thought that this was installed automatically when installing `@recordreplay/replay-node-cli`. So nothing wrong on your end
